name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-

    - name: Build with Maven
        run: mvn -B package --file pom.xml

    - name: Set SHORT_SHA
        id: vars
        run: echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"

    - name: Publish to GitHub Packages Apache Maven
        run: mvn -B -s $GITHUB_WORKSPACE/deploy_settings.xml clean deploy --batch-mode --no-transfer-progress -Drevision=${{ steps.vars.outputs.SHORT_SHA }}
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
